name: build and tests

on:
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_TAG: ghcr.io/openai-all-stars/executor:latest

jobs:

    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3
        - name: Login
          run: |
            echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        - name: Build and Publish
          run: |
            docker build . --tag ${{ env.DOCKER_TAG }}
            docker push ${{ env.DOCKER_TAG }}

    tests:
        needs: build
        name: Tests
        runs-on: ubuntu-latest

        steps:
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: 3.11
        - uses: actions/checkout@v3
        - name: Install tox
          run: pip install tox
        - name: Run tests
          run: tox
